### PR TITLE
Added docs for docker installation

### PR DESCRIPTION
**Pull request by Eeeeelias**
Really cool content bar! I set it up on my jellyfin docker instance and thought that somebody else might benefit from a little guidance there. Thus, I wrote a few docs for exactly this. 

Let me know if it's unclear but it should just work! :)

### CODE REVIEW

**Review by tedhinklater — COMMENTED** [review]
Thank you!! Saved me from setting up another PC to figure out docker <3

**Comment by Vinod1452** [comment]
Hi, I have installed jelltfin as docker container, but i cant see jelltyfin-web folder anywhere in jellyfin config folder, also cant find file named "home-html..chunk.js" so i could edit it. I mounted Jellyfin config folder as bind volume using portainer
image

image

**Comment by Eeeeelias** [comment]
Hi, the jellyfin-web folder is not in the config folder. The container path is `/jellyfin/jellyfin-web/`; in there you'll also find the `home-html.<RANDOMSTRING>.chunk.js` file that you can edit :).
If you have any issues finding it, let me know

**Comment by Vinod1452** [comment]
Thanks for quick reply
I am using Linuxserver.io image, found folder and file here "/usr/share/jellyfin/web/". Will follow instructions and update.

**Pull request merged**
