### PR TITLE
Muting Trailers option added to list.txt

### PR DESCRIPTION
**Pull request by Zoft123**
By putting MuteOn or MuteOff on the same line as Spotlight in the list.txt you can have the trailer play with full volume or play muted. If there isn't a selection included it will default to MuteOff.

### CODE REVIEW

**Comment by Mercedezs** [comment]
I tested what you did, I believe I did it the way you mentioned, but it didn't work for me

**Comment by Zoft123** [comment]
> I tested what you did, I believe I did it the way you mentioned, but it didn't work for me

Make sure to clear your browser data for your webpage after implementing it.

**Comment by Mercedezs** [comment]
You were right; I was only using Ctrl+F5 to clear the cache, but it wasn’t enough to clear the browser cache. I deleted all the browser cache, and it worked. I did some tests, and it seems to be 100%. Thank you!

**Comment by Isaiasgamedev** [comment]
i put muteon but is not working

**Review by Isaiasgamedev — APPROVED** [review]

**Comment by tedhinklater** [comment]
You can just change this to mute: 1 in spotlight.html

Screenshot 2024-11-21 191658

**Comment by Isaiasgamedev** [comment]
you need to accept the pull request i get the changes and put on spotlight fullscreen and works fine on here, so i belive you need just to update the spotliths

**Comment by tedhinklater** [comment]
I stopped edits for a while because Seth was making a big update, which should be coming soon and any changes would be made redundant. We have to fix these bugs though and I appreciate the time people have taken to fix things.

**Pull request merged**
